- name: install httpd
  yum:
    name: httpd
    state: installed
- name: start and enable httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
- name: permit traffic in default zone for https service
  firewalld:
    port: "{{ http_port }}"
    permanent: yes
    state: enabled
  notify:
    - reload service firewalld
- name: template render
  template: 
     src: index.html.j2
     dest: "{{ html_page_dest }}"
